### ISSUE TITLE
How to format Google Drive link?

### ISSUE THREAD

**Issue by eliasbenb** [RafaeNoor/GDrive-Party#8]
I can't seem to figure out how to format the Google Drive sharable link.
I've tried these formats:
- https://drive.google.com/uc?export=download&id=[ID]
- https://drive.google.com/file/d/[ID]/view?usp=sharing\

I'm using the demo website on Heroku.

**Comment by RafaeNoor** [comment]
Hey @eliasbenb, you don't have to manually format the url now. [Here](https://github.com/RafaeNoor/GDrive-Party/blob/master/src/components/URLFormatter.js) I added a `URLFormatter` class which automatically formats the URL when the user supplies. So whatever url you get when you get the Editable shareable link you should just enter that and it'll do it on your side. Could you check with that?

**Comment by eliasbenb** [comment]
> Hey @eliasbenb, you don't have to manually format the url now. [Here](https://github.com/RafaeNoor/GDrive-Party/blob/master/src/components/URLFormatter.js) I added a `URLFormatter` class which automatically formats the URL when the user supplies. So whatever url you get when you get the Editable shareable link you should just enter that and it'll do it on your side. Could you check with that?

I've tried that, it's just stuck on a blank video player

**Comment by RafaeNoor** [comment]
Could you share the link with me?

**Comment by eliasbenb** [comment]
> Could you share the link with me?

aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xSXRoZW05WnZ6QmlqSFRrekZfMDRhSEZ4UEFZVjZ2WEsvdmlldz91c3A9c2hhcmluZw==

https://www.base64decode.org/

**Comment by RafaeNoor** [comment]
Also, there's currently an issue with large files in particular. Streaming those doesn't work because google has some safety checks. How large is the file you are trying to stream?

**Comment by eliasbenb** [comment]
> Also, there's currently an issue with large files in particular. Streaming those doesn't work because google has some safety checks. How large is the file you are trying to stream?

I've tried 2 files, one was 500mb the one I shared was 2gb

**Comment by RafaeNoor** [comment]
Yeah, I'm guessing it's because of file size. It's an [Open issue](https://github.com/RafaeNoor/GDrive-Party/issues/1) right now. Sorry about that.

**Comment by eliasbenb** [comment]
> Yeah, I'm guessing it's because of file size. It's an [Open issue](https://github.com/RafaeNoor/GDrive-Party/issues/1) right now. Sorry about that.

So how small are we talking? What's the size limit?
